import sys
import random


TAGS = [
    '#adopt',
    '#adorable',
    '#animal',
    '#animallovers',
    '#animals',
    '#aww',
    '#bestcats',
    '#bestcats_oftheworld',
    '#bestmeow',
    '#blackcat',
    '#cat',
    '#cat_features',
    '#cat_of_instagram',
    '#catdog',
    '#cateye',
    '#cateyes',
    '#catinstagram',
    '#catlady',
    '#catlife',
    '#catlove',
    '#catlover',
    '#catlovers',
    '#catloversclub',
    '#catmemes',
    '#catmom',
    '#catofinstagram',
    '#catofteday',
    '#catoftheday',
    '#catperson',
    '#catphoto',
    '#catphotos',
    '#cats',
    '#cats_of_instagram',
    '#catsagram',
    '#catsfollowers',
    '#catsgram',
    '#catslover',
    '#catsofig',
    '#catsofinsta',
    '#catsofinstagram',
    '#catsofreddit',
    '#catsoftheworld',
    '#catsofworld',
    '#catsonly',
    '#catstagram',
    '#cattvideo',
    '#catworld',
    '#coolcats',
    '#crazycatlady',
    '#cursedcat',
    '#cursedcatimages',
    '#cursedcats',
    '#cursedkitties',
    '#cursedpets',
    '#cute',
    '#cutecat',
    '#cutecatcrew',
    '#cutecats',
    '#cutest',
    '#epiccats',
    '#excellent_cats',
    '#funny',
    '#funnycat',
    '#furry',
    '#gato',
    '#gatos',
    '#igcats',
    '#ilovecat',
    '#ilovemycat',
    '#insta',
    '#instaanimal',
    '#instacat',
    '#instacat_meows',
    '#instacats',
    '#instagood',
    '#instagram',
    '#instagramcats',
    '#instakitty',
    '#katt',
    '#kitten',
    '#kittens',
    '#kittensofinstagram',
    '#kitties',
    '#kitty',
    '#kittycat',
    '#kittylove',
    '#kittymemes',
    '#kucing',
    '#lovecats',
    '#lovekittens',
    '#mascota',
    '#meow',
    '#meowbox',
    '#munchkin',
    '#mycat',
    '#nature',
    '#paw',
    '#paws',
    '#pet',
    '#petmemes',
    '#pets',
    '#petsagram',
    '#petscorner',
    '#petstagram',
    '#photooftheday',
    '#picneko',
    '#purr',
    '#thedailykitten',
    '#topcatphoto',
    '#weeklyfluff',
    '#weirdcats',
    '#whitecat',
    '#zoo',
    '#кот',
    '#котенок',
    '#кошка',
    '#ねこ',
    '#ねこ部',
    '#ネコ',
    '#猫',
    '#고양이',
    '#냥스타그램',
]


def gen(limit=15):
    return random.sample(TAGS, limit)


if __name__ == '__main__':
    if len(sys.argv) > 1:
        limit = int(sys.argv[1])
    else:
        limit = 15
    print(' '.join(gen(limit)))